### ISSUE TITLE
Unpacking zip failed

### ISSUE THREAD

**Issue by stinuz** [creador/ti_recover#2]
I get the following error on windows & mac with clean install

Error: Error running instance method
brut.androlib.AndrolibException: brut.directory.DirectoryException: java.util.zip.ZipException: error in opening zip file
        at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:272)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:96)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: brut.directory.DirectoryException: java.util.zip.ZipException: error in opening zip file
        at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
        at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
        at brut.directory.ExtFile.getDirectory(ExtFile.java:51)
        at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:270)
        ... 5 more
Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.zip.ZipFile.<init>(ZipFile.java:163)
        at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
        ... 8 more

    at Error (native)
    at Object.extractAPK [as extract] (C:\Projecten\daisy\ti_recover-master\node_modules\apk_unpack\apk_unpack.js:64:11)
    at Object.init (C:\Projecten\daisy\ti_recover-master\ti_recover.js:41:7)
    at Object.<anonymous> (C:\Projecten\daisy\ti_recover-master\cli:25:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

**Comment by creador** [comment]
Hi @stinuz , can you post the command you use to install ti_recover ? Please note it has to be installed globally: `npm install -g ti_recover`
