### ISSUE TITLE
Error during installation or run

### ISSUE THREAD

**Issue by rbrown256** [creador/ti_recover#8]
Hi,

I'm trying to install this on Kali and get the following error:

```
npm i ti_recover

> java@0.8.0 install /root/Documents/ti_recover/node_modules/java
> node-gyp rebuild

make: Entering directory '/root/Documents/ti_recover/node_modules/java/build'
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/java.o
In file included from ../../nan/nan.h:190,
                 from ../src/java.h:9,
                 from ../src/java.cpp:1:
../../nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../../nan/nan_maybe_43_inl.h:88:15: error: ‘class v8::Object’ has no member named ‘ForceSet
```

any advice?

I also tried on node v8 as I saw the above issue with other projects, and it installs, but I get this error when running:

```
ti_recover /mnt/hgfs/Host\ Home/x.apk ./output

Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Appcelerator Titanium - APK Source Code Recovery Tool
/opt/node-v8.17.0-linux-x64/lib/node_modules/ti_recover/node_modules/java/lib/nodeJavaBridge.js:233
    return java.newInstanceSync.apply(java, args);
                                ^

Error: Error creating class
java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

    at new javaClassConstructorProxy (/opt/node-v8.17.0-linux-x64/lib/node_modules/ti_recover/node_modules/java/lib/nodeJavaBridge.js:233:33)
    at Object.extractAPK [as extract] (/opt/node-v8.17.0-linux-x64/lib/node_modules/ti_recover/node_modules/apk_unpack/apk_unpack.js:59:18)
    at Object.init (/opt/node-v8.17.0-linux-x64/lib/node_modules/ti_recover/ti_recover.js:41:7)
    at Object.<anonymous> (/opt/node-v8.17.0-linux-x64/lib/node_modules/ti_recover/cli:25:10)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
```

A solution to either problem would be good, but seems like I got further by downgrading Node to v8?

Your help is much appreciated

**Comment by creador** [comment]
Hi there, 

First you have to use Node version 8 for this to work, and also make sure you javac installed. Also, you need to install ti_recover globally for it to work (npm i -g ti_recover). The code for ti_recover is almost 4 years old now, so also it'll only work for APKs made for up to Android 6.

Best of lucks.

**Comment by rbrown256** [comment]
Many thanks for your response.

I did get it working by using the global option and v8, however, with no results as such (just the working `_tmp` directory, with no extra files in it).

Shame it hasn't been updated, as this looked like an awesome tool, and appears to be the only one out there. It would have been perfect for the pentesting I'm currently working on. Anyway, no problem and take it easy!
